name: shoe_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

#---------------------------PACKAGES--------------------#
dependencies:
  flutter:
    sdk: flutter

# Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.4.0
  lottie: ^3.1.2
  connectivity_plus: ^6.0.3




  # Icons Packages
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8


  # State Management Packages
  get: ^4.6.6


# Product Specific Packages
  readmore: ^3.0.0
  carousel_slider: ^4.2.1


# Local storage Packages
  get_storage: ^2.1.1

# Firebase packages
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5


#---------------------------PACKAGES END--------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  #---------------------------LOCAL ASSETS--------------------#

  assets:
    - assets/images/new_onboarding/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/products/
    - assets/images/reviews/
    - assets/logos/
    - assets/icons/categories/
    - assets/icons/payment_methods/

  #---------------------------LOCAL FONTS--------------------#

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800



































