// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-_2S2XezlBbD3UNbi4tncxTkT0H-7oIA',
    appId: '1:585860848213:web:b87b20a1190270201c92dc',
    messagingSenderId: '585860848213',
    projectId: 'ecommerce-a304a',
    authDomain: 'ecommerce-a304a.firebaseapp.com',
    storageBucket: 'ecommerce-a304a.appspot.com',
    measurementId: 'G-YJHMZLJ2LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyiaO6QgoFtv5obchI4qEsoRCAP-nR5M0',
    appId: '1:585860848213:android:82580908c973a87f1c92dc',
    messagingSenderId: '585860848213',
    projectId: 'ecommerce-a304a',
    storageBucket: 'ecommerce-a304a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm0D16V2sihuuCSD578RgycTELn6XE3tU',
    appId: '1:585860848213:ios:6fec241843b97cc51c92dc',
    messagingSenderId: '585860848213',
    projectId: 'ecommerce-a304a',
    storageBucket: 'ecommerce-a304a.appspot.com',
    iosClientId: '585860848213-8dvkocr5e1967e5v8l5b4jiau0q2hotv.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoeApp',
  );

}